version: '3'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres
    hostname: myhost
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/data/db